// packages/angular-lang/src/lib/library.ts
import type { Type } from "@angular/core";
import {
  createLibrary as coreCreateLibrary,
  defineComponent as coreDefineComponent,
  type ComponentRenderProps as CoreComponentRenderProps,
  type DefinedComponent as CoreDefinedComponent,
  type Library as CoreLibrary,
  type LibraryDefinition as CoreLibraryDefinition,
} from "@openuidev/lang-core";
import type { $ZodObject } from "zod/v4/core";

export type {
  ComponentGroup,
  PromptOptions,
  SubComponentOf,
  ToolDescriptor,
} from "@openuidev/lang-core";

export interface ComponentRenderProps<P = Record<string, unknown>> extends CoreComponentRenderProps<
  P,
  unknown
> {}

/**
 * Angular component type registered in an OpenUI library.
 *
 * The runtime treats this value opaquely and instantiates it through Angular's
 * dynamic component APIs. The package does not require the component instance
 * to implement a specific interface at the type level during v0.1.
 */
export type ComponentRenderer = Type<unknown>;

export type DefinedComponent<T extends $ZodObject = $ZodObject> = CoreDefinedComponent<
  T,
  ComponentRenderer
>;

export type Library = CoreLibrary<ComponentRenderer>;

export type LibraryDefinition = CoreLibraryDefinition<ComponentRenderer>;

/**
 * Define a single Angular-rendered OpenUI component.
 */
export function defineComponent<T extends $ZodObject>(config: {
  name: string;
  props: T;
  description: string;
  component: ComponentRenderer;
}): DefinedComponent<T> {
  return coreDefineComponent<T, ComponentRenderer>(config);
}

/**
 * Create an Angular OpenUI component library.
 */
export function createLibrary(input: LibraryDefinition): Library {
  return coreCreateLibrary(input) as Library;
}

// packages/solid-lang/src/library.ts
import {
  createLibrary as coreCreateLibrary,
  defineComponent as coreDefineComponent,
  type DefinedComponent as CoreDefinedComponent,
  type Library as CoreLibrary,
  type LibraryDefinition as CoreLibraryDefinition,
  type ComponentRenderProps as CoreRenderProps,
} from "@openuidev/lang-core";
import type { JSX } from "solid-js";
import { z } from "zod";

export type {
  ComponentGroup,
  LibraryJSONSchema,
  PromptOptions,
  SubComponentOf,
  ToolDescriptor,
} from "@openuidev/lang-core";

export type ComponentRenderProps<P = Record<string, unknown>> = CoreRenderProps<P, JSX.Element>;

export type ComponentRenderer<P = Record<string, unknown>> = (
  props: ComponentRenderProps<P>,
) => JSX.Element;

export type DefinedComponent<T extends z.ZodObject<any> = z.ZodObject<any>> = CoreDefinedComponent<
  T,
  ComponentRenderer<z.infer<T>>
>;

export type Library = CoreLibrary<ComponentRenderer<any>>;

export type LibraryDefinition = CoreLibraryDefinition<ComponentRenderer<any>>;

export function defineComponent<T extends z.ZodObject<any>>(config: {
  name: string;
  props: T;
  description: string;
  component: ComponentRenderer<z.infer<T>>;
}): DefinedComponent<T> {
  return coreDefineComponent<T, ComponentRenderer<z.infer<T>>>(config);
}

export function createLibrary(input: LibraryDefinition): Library {
  return coreCreateLibrary<ComponentRenderer<any>>(input) as Library;
}
