// examples/svelte-chat/src/lib/components/library/CodeBlock.svelte
<script lang="ts">
	import type { ComponentRenderProps } from "@openuidev/svelte-lang";

	interface Props
		extends ComponentRenderProps<{
			language: string;
			codeString: string;
		}> {}

	let { props }: Props = $props();
</script>

<div class="overflow-hidden rounded-lg border bg-zinc-950">
	<div class="flex items-center border-b border-zinc-800 bg-zinc-900 px-4 py-2">
		<span class="text-xs font-medium uppercase tracking-wider text-zinc-400">
			{props.language}
		</span>
	</div>
	<pre class="m-0 overflow-x-auto p-4"><code
			class="font-mono text-sm leading-relaxed text-zinc-200">{props.codeString}</code
		></pre>
</div>

// docs/components/overview-components/code-block.tsx
"use client";

import { useState } from "react";

interface CodeBlockProps {
  code: string;
  title?: string;
  language?: string;
  codeBlockClassName?: string;
  className?: string;
}

export function CodeBlock({
  code,
  title,
  codeBlockClassName = "",
  className = "",
}: CodeBlockProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div
      className={`overflow-hidden rounded-lg border border-slate-200 dark:border-slate-800 flex flex-col ${className}`}
    >
      {title && (
        <div className="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-4 py-2.5 dark:border-slate-800 dark:bg-slate-900/50">
          <span className="text-xs font-medium text-slate-600 dark:text-slate-400">{title}</span>
          <button
            onClick={handleCopy}
            className="text-xs text-slate-500 transition-colors hover:text-slate-700 dark:hover:text-slate-300"
          >
            {copied ? "Copied!" : "Copy"}
          </button>
        </div>
      )}
      <pre
        className={`grow-1 overflow-x-auto bg-slate-950 p-4 text-sm leading-relaxed text-slate-300 ${codeBlockClassName}`}
      >
        <code>{code}</code>
      </pre>
    </div>
  );
}
