// packages/svelte-lang/src/Renderer.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { setOpenUIContext } from "./context.js";
  import type { ComponentRenderer, DefinedComponent, Library } from "./library.js";
  import type { ActionEvent, ElementNode, ParseResult } from "./parser/types.js";
  import { createOpenUIState } from "./stores/openui.svelte.js";
  import RenderNode from "./RenderNode.svelte";

  interface Props {
    /** Raw response text (openui-lang code). */
    response: string | null;
    /** Component library from createLibrary(). */
    library: Library;
    /** Whether the LLM is still streaming (form interactions disabled during streaming). */
    isStreaming?: boolean;
    /** Callback when a component triggers an action. */
    onAction?: (event: ActionEvent) => void;
    /**
     * Called whenever a form field value changes. Receives the raw form state map.
     */
    onStateUpdate?: (state: Record<string, any>) => void;
    /**
     * Initial form state to hydrate on load.
     */
    initialState?: Record<string, any>;
    /** Called whenever the parse result changes. */
    onParseResult?: (result: ParseResult | null) => void;
  }

  let {
    response,
    library,
    isStreaming = false,
    onAction,
    onStateUpdate,
    initialState,
    onParseResult,
  }: Props = $props();

  /**
   * Recursively renders a parsed value (element, array, primitive)
   * into Svelte-renderable content. Used by component renderers.
   *
   * In Svelte, we return the raw data and let RenderNode handle rendering.
   * This function is passed to component renderers so they can render
   * nested children.
   */
  function renderDeep(value: unknown): any {
    return value;
  }

  const state = createOpenUIState(
    () => ({
      response,
      library,
      isStreaming,
      onAction,
      onStateUpdate,
      initialState,
    }),
    renderDeep as any,
  );

  // Notify parent when parse result changes
  $effect(() => {
    onParseResult?.(state.result);
  });

  // Set the context for child components
  setOpenUIContext(state.contextValue);
</script>

{#if state.result?.root}
  <RenderNode node={state.result.root} {library} />
{/if}

// packages/lang-react/src/Renderer.tsx
import React, { Component, Fragment, useEffect } from "react";
import { OpenUIContext, useOpenUI, useRenderNode } from "./context";
import { useOpenUIState } from "./hooks/useOpenUIState";
import type { ComponentRenderer, Library } from "./library";
import type { ActionEvent, ElementNode, ParseResult } from "./parser/types";

export interface RendererProps {
  /** Raw response text (openui-lang code). */
  response: string | null;
  /** Component library from createLibrary(). */
  library: Library;
  /** Whether the LLM is still streaming (form interactions disabled during streaming). */
  isStreaming?: boolean;
  /** Callback when a component triggers an action. */
  onAction?: (event: ActionEvent) => void;
  /**
   * Called whenever a form field value changes. Receives the raw form state map.
   * The consumer decides how to persist this (e.g. embed in message, store separately).
   */
  onStateUpdate?: (state: Record<string, any>) => void;
  /**
   * Initial form state to hydrate on load (e.g. from a previously persisted message).
   * Shape: { formName: { fieldName: { value, componentType } } }
   */
  initialState?: Record<string, any>;
  /** Called whenever the parse result changes. */
  onParseResult?: (result: ParseResult | null) => void;
}

// ─── Error boundary ───

interface ErrorBoundaryProps {
  children: React.ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
}

class ElementErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  private lastValidChildren: React.ReactNode = null;

  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(): ErrorBoundaryState {
    return { hasError: true };
  }

  componentDidMount(): void {
    if (!this.state.hasError) {
      this.lastValidChildren = this.props.children;
    }
  }

  componentDidUpdate(prevProps: ErrorBoundaryProps): void {
    if (!this.state.hasError) {
      this.lastValidChildren = this.props.children;
    }
    if (this.state.hasError && prevProps.children !== this.props.children) {
      this.setState({ hasError: false });
    }
  }

  componentDidCatch(error: Error, info: React.ErrorInfo): void {
    console.error("[openui] Component render error:", error, info);
  }

  render() {
    if (this.state.hasError) {
      return this.lastValidChildren;
    }
    return this.props.children;
  }
}

// ─── Internal rendering ───

/**
 * Recursively renders a parsed value (element, array, primitive)
 * into React nodes.
 */
function renderDeep(value: unknown): React.ReactNode {
  if (value == null) return null;
  if (typeof value === "string") return value;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    return value.map((v, i) => <Fragment key={i}>{renderDeep(v)}</Fragment>);
  }

  if (typeof value === "object" && value !== null) {
    const obj = value as Record<string, unknown>;
    if (obj.type === "element") {
      return <RenderNode node={obj as unknown as ElementNode} />;
    }
  }

  return null;
}

/**
 * Renders a single ElementNode.
 */
function RenderNode({ node }: { node: ElementNode }) {
  const { library } = useOpenUI();
  const Comp = library.components[node.typeName]?.component;

  if (!Comp) return null;

  return (
    <ElementErrorBoundary>
      <RenderNodeInner el={node} Comp={Comp} />
    </ElementErrorBoundary>
  );
}

/**
 * Renders a resolved element using its renderer. Gets renderNode from context.
 */
function RenderNodeInner({ el, Comp }: { el: ElementNode; Comp: ComponentRenderer<any> }) {
  const renderNode = useRenderNode();
  const { library } = useOpenUI();

  // Handle elements that have positional `args` instead of named `props`
  let props = el.props;
  if (!props) {
    const args = (el as any).args as unknown[] | undefined;
    if (args) {
      const def = library.components[el.typeName];
      if (def) {
        const fieldNames = Object.keys(def.props.shape);
        props = {};
        for (let i = 0; i < fieldNames.length && i < args.length; i++) {
          props[fieldNames[i]] = args[i];
        }
      }
    }
    props = props ?? {};
  }

  return <Comp props={props} renderNode={renderNode} />;
}

// ─── Public component ───

export function Renderer({
  response,
  library,
  isStreaming = false,
  onAction,
  onStateUpdate,
  initialState,
  onParseResult,
}: RendererProps) {
  const { result, contextValue } = useOpenUIState(
    {
      response,
      library,
      isStreaming,
      onAction,
      onStateUpdate,
      initialState,
    },
    renderDeep,
  );

  useEffect(() => {
    onParseResult?.(result);
  }, [result, onParseResult]);

  if (!result?.root) {
    return null;
  }

  return (
    <OpenUIContext.Provider value={contextValue}>
      <RenderNode node={result.root} />
    </OpenUIContext.Provider>
  );
}
