// examples/svelte-chat/src/lib/components/library/CodeBlock.svelte
<script lang="ts">
	import type { ComponentRenderProps } from "@openuidev/svelte-lang";

	interface Props
		extends ComponentRenderProps<{
			language: string;
			codeString: string;
		}> {}

	let { props }: Props = $props();
</script>

<div class="overflow-hidden rounded-lg border bg-zinc-950">
	<div class="flex items-center border-b border-zinc-800 bg-zinc-900 px-4 py-2">
		<span class="text-xs font-medium uppercase tracking-wider text-zinc-400">
			{props.language}
		</span>
	</div>
	<pre class="m-0 overflow-x-auto p-4"><code
			class="font-mono text-sm leading-relaxed text-zinc-200">{props.codeString}</code
		></pre>
</div>

// examples/shadcn-chat/src/lib/shadcn-genui/components/code-block.tsx
"use client";

import { defineComponent } from "@openuidev/react-lang";
import { z } from "zod";

const CodeBlockSchema = z.object({
  code: z.string(),
  language: z.string().optional(),
  title: z.string().optional(),
});

export const CodeBlock = defineComponent({
  name: "CodeBlock",
  props: CodeBlockSchema,
  description: "Syntax-highlighted code block with optional language and title.",
  component: ({ props }) => {
    const code = props.code == null ? "" : String(props.code);
    return (
      <div className="rounded-lg border bg-muted">
        {props.title && (
          <div className="border-b px-4 py-2 text-xs font-medium text-muted-foreground">
            {props.title}
            {props.language && (
              <span className="ml-2 text-xs opacity-60">{props.language}</span>
            )}
          </div>
        )}
        <pre className="overflow-x-auto p-4">
          <code className="text-sm font-mono">{code}</code>
        </pre>
      </div>
    );
  },
});
