// examples/svelte-chat/src/lib/components/library/Separator.svelte
<script lang="ts">
	import type { ComponentRenderProps } from "@openuidev/svelte-lang";
	import { Separator } from "$lib/components/ui/separator/index.js";

	interface Props
		extends ComponentRenderProps<{
			orientation?: "horizontal" | "vertical";
		}> {}

	let { props }: Props = $props();
</script>

<Separator orientation={props.orientation ?? "horizontal"} />

// examples/shadcn-chat/src/lib/shadcn-genui/components/separator.tsx
"use client";

import { Separator as ShadcnSeparator } from "@/components/ui/separator";
import { defineComponent } from "@openuidev/react-lang";
import { z } from "zod";

const SeparatorSchema = z.object({
  orientation: z.enum(["horizontal", "vertical"]).optional(),
});

export const Separator = defineComponent({
  name: "Separator",
  props: SeparatorSchema,
  description: 'Horizontal or vertical rule. orientation: "horizontal" | "vertical".',
  component: ({ props }) => (
    <ShadcnSeparator orientation={props.orientation ?? "horizontal"} />
  ),
});
