// examples/heroui-chat/src/lib/heroui-genui/components/text-content.tsx
"use client";

import { defineComponent } from "@openuidev/react-lang";
import { z } from "zod";

const TextContentSchema = z.object({
  text: z.string(),
  size: z.enum(["small", "default", "large", "small-heavy", "large-heavy"]).optional(),
});

const sizeClasses: Record<string, string> = {
  small: "text-sm text-muted",
  default: "text-base",
  large: "text-lg",
  "small-heavy": "text-sm font-semibold",
  "large-heavy": "text-lg font-semibold",
};

export const TextContent = defineComponent({
  name: "TextContent",
  props: TextContentSchema,
  description:
    'Plain text block. size: "small" | "default" | "large" | "small-heavy" | "large-heavy".',
  component: ({ props }) => {
    const text = props.text == null ? "" : String(props.text);
    const size = (props.size as string) ?? "default";
    const cls = sizeClasses[size] ?? sizeClasses["default"];
    return <p className={cls}>{text}</p>;
  },
});

// examples/svelte-chat/src/lib/components/library/TextContent.svelte
<script lang="ts">
	import type { ComponentRenderProps } from "@openuidev/svelte-lang";

	interface Props
		extends ComponentRenderProps<{
			text: string;
			size?: "small" | "default" | "large" | "small-heavy" | "large-heavy";
		}> {}

	let { props }: Props = $props();

	const sizeClass: Record<string, string> = {
		small: "text-sm text-muted-foreground",
		default: "text-base text-foreground",
		large: "text-lg text-foreground",
		"small-heavy": "text-sm font-semibold text-foreground",
		"large-heavy": "text-2xl font-bold text-foreground",
	};

	const className = $derived(sizeClass[props.size ?? "default"]);
</script>

<p class="{className} m-0 leading-relaxed">{props.text}</p>
